### ISSUE TITLE
Test out and explore ECDC tool

### ISSUE THREAD

**Issue by karinlag** [NorwegianVeterinaryInstitute/ORION_HandBook#20]
User manual is here:

https://drive.google.com/open?id=15WrFQMKKIJVUJSlnxYARWkMotezgcC2D

**Comment by ajkarloss** [comment]
TESSY: The European Surveillance System

The ECDC App: The ECDC WGS upload application is a multi-platform desktop client application intended for isolate-based reporting to TESSy, for isolates with associated WGS data. It can be configured to submit data to TESSy (mandatory), ENA (optional), and ECDC SFTP server (optional). It can submit assemblies as well as raw read data. 

Its a desktop application for submitting data to Tessy. The manual shows how to configure the app so that your data will be submitted to TESSY Manually/routinely.

**Comment by ajkarloss** [comment]
I was able to Download and Install. And, looked at all the all the options and configuration they have mentioned.

**Comment by ajkarloss** [comment]
Nothing much to add.
